/* The following code was generated by JFlex 1.4.1 on 7/3/16 8:35 AM */

package Example;

import java_cup.runtime.SymbolFactory;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 7/3/16 8:35 AM from the specification file
 * <tt>/Users/Tomi/Desktop/TLA/tpe-tla/jflex/Scanner.jflex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 43, 18,  0, 43, 43,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    17,  0,  1,  5,  6, 23,  0,  0, 24, 25, 21, 19,  0, 20,  0, 22, 
    42,  3,  3,  3,  3,  3,  3,  3,  3,  3,  0,  0, 26, 38, 37,  0, 
     0,  2, 27,  2,  2, 28, 31, 29, 33, 30,  2,  2,  2,  2,  7,  2, 
     2,  2,  2, 32,  2,  2,  2,  2,  2,  2,  2,  0,  0,  0,  0,  4, 
     0, 41,  2, 13,  9, 10, 11,  2,  2, 34,  2,  2, 35,  2, 15, 14, 
    36,  2, 40, 16, 12,  8,  2,  2,  2,  2,  2,  0,  0,  0, 39,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\3\1\1\2\7\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\4\1\1\15"+
    "\1\16\1\17\1\1\1\2\1\0\1\20\1\21\2\0"+
    "\6\21\1\22\1\23\1\24\1\25\1\26\1\27\2\21"+
    "\1\30\1\31\1\21\1\32\1\21\1\33\1\34\1\35"+
    "\4\21\1\36\3\21\1\37\1\40\1\21\1\41\3\21"+
    "\1\42\1\43\1\21\1\44\1\21\1\0\1\45\1\0"+
    "\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0160\0\u018c\0\u01b8\0\u01e4\0\54\0\54\0\54\0\54"+
    "\0\54\0\54\0\54\0\54\0\54\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\54\0\54\0\u02ec\0\u0318\0\54\0\130"+
    "\0\54\0\204\0\u0344\0\u0370\0\u039c\0\u03c8\0\u03f4\0\u0420"+
    "\0\u044c\0\u0478\0\204\0\54\0\54\0\54\0\54\0\54"+
    "\0\u04a4\0\u04d0\0\204\0\204\0\u04fc\0\54\0\u0528\0\u0344"+
    "\0\u0370\0\204\0\u0554\0\u0580\0\u05ac\0\u05d8\0\204\0\u0604"+
    "\0\u0630\0\u065c\0\204\0\204\0\u0688\0\204\0\u06b4\0\u06e0"+
    "\0\u070c\0\204\0\204\0\u0738\0\204\0\u0764\0\u0790\0\204"+
    "\0\u07bc\0\u07bc";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\3\4"+
    "\1\10\1\11\1\12\1\13\1\14\2\4\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\3\4\1\30\2\4\1\31\1\32\1\4\1\33"+
    "\1\34\1\35\1\4\1\36\1\37\1\15\54\0\1\40"+
    "\1\41\52\40\2\0\3\42\2\0\12\42\12\0\12\42"+
    "\3\0\3\42\4\0\1\5\46\0\1\5\3\0\1\43"+
    "\4\0\12\43\12\0\12\43\3\0\2\43\4\0\1\44"+
    "\4\0\12\44\12\0\12\44\3\0\2\44\4\0\3\42"+
    "\2\0\10\42\1\45\1\42\12\0\10\42\1\46\1\42"+
    "\3\0\3\42\3\0\3\42\2\0\12\42\12\0\12\42"+
    "\3\0\1\42\1\47\1\42\3\0\3\42\2\0\12\42"+
    "\12\0\12\42\3\0\1\50\2\42\3\0\3\42\2\0"+
    "\7\42\1\51\2\42\12\0\12\42\3\0\3\42\3\0"+
    "\3\42\2\0\1\42\1\52\10\42\12\0\12\42\3\0"+
    "\1\53\2\42\24\0\1\54\1\55\1\56\1\57\3\0"+
    "\1\60\23\0\3\42\2\0\12\42\12\0\1\42\1\61"+
    "\10\42\3\0\3\42\3\0\3\42\2\0\12\42\12\0"+
    "\3\42\1\62\6\42\3\0\3\42\3\0\3\42\2\0"+
    "\4\42\1\63\3\42\1\64\1\42\12\0\12\42\3\0"+
    "\3\42\3\0\3\42\2\0\7\42\1\65\2\42\12\0"+
    "\12\42\3\0\3\42\47\0\1\66\7\0\3\42\2\0"+
    "\10\42\1\67\1\42\12\0\12\42\3\0\3\42\3\0"+
    "\3\70\2\0\12\70\12\0\12\70\3\0\3\70\3\0"+
    "\3\71\2\0\12\71\12\0\12\71\3\0\3\71\3\0"+
    "\3\42\2\0\2\42\1\72\7\42\12\0\12\42\3\0"+
    "\3\42\3\0\3\42\2\0\11\42\1\73\12\0\12\42"+
    "\3\0\3\42\3\0\3\42\2\0\12\42\12\0\10\42"+
    "\1\74\1\42\3\0\3\42\3\0\3\42\2\0\1\42"+
    "\1\75\10\42\12\0\12\42\3\0\3\42\3\0\3\42"+
    "\2\0\10\42\1\76\1\42\12\0\12\42\3\0\3\42"+
    "\3\0\3\42\2\0\5\42\1\77\4\42\12\0\12\42"+
    "\3\0\3\42\3\0\3\42\2\0\12\42\12\0\2\42"+
    "\1\100\7\42\3\0\3\42\3\0\3\42\2\0\1\101"+
    "\11\42\12\0\12\42\3\0\3\42\3\0\3\42\2\0"+
    "\7\42\1\102\2\42\12\0\12\42\3\0\3\42\3\0"+
    "\3\42\2\0\2\42\1\103\7\42\12\0\12\42\3\0"+
    "\3\42\3\0\3\42\2\0\3\42\1\104\6\42\12\0"+
    "\12\42\3\0\3\42\3\0\3\42\2\0\11\42\1\105"+
    "\12\0\12\42\3\0\3\42\3\0\3\42\2\0\3\42"+
    "\1\106\6\42\12\0\12\42\3\0\3\42\3\0\3\42"+
    "\2\0\11\42\1\107\12\0\12\42\3\0\3\42\3\0"+
    "\3\42\2\0\12\42\12\0\3\42\1\110\6\42\3\0"+
    "\3\42\3\0\3\42\2\0\12\42\12\0\3\42\1\111"+
    "\6\42\3\0\3\42\3\0\3\42\2\0\12\42\12\0"+
    "\11\42\1\112\3\0\3\42\3\0\3\42\2\0\3\42"+
    "\1\113\6\42\12\0\12\42\3\0\3\42\3\0\3\42"+
    "\2\0\5\42\1\114\4\42\12\0\12\42\3\0\3\42"+
    "\3\0\3\42\2\0\1\115\11\42\12\0\12\42\3\0"+
    "\3\42\3\0\3\42\2\0\12\42\12\0\5\42\1\116"+
    "\4\42\3\0\3\42\3\0\3\42\2\0\12\42\1\117"+
    "\11\0\12\42\3\0\3\42\3\0\3\42\2\0\12\42"+
    "\12\0\6\42\1\120\3\42\3\0\3\42\3\0\1\121"+
    "\4\0\12\121\12\0\12\121\3\0\2\121\4\0\3\122"+
    "\2\0\12\122\12\0\12\122\3\0\3\122\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2024];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\12\1\11\11\5\1\2\11\2\1\1\11"+
    "\1\0\1\11\1\1\2\0\7\1\5\11\5\1\1\11"+
    "\30\1\1\0\1\1\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public Scanner(java.io.InputStream r, SymbolFactory sf){
		this(r);
		this.sf=sf;
	}
	private SymbolFactory sf;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { return sf.newSymbol("Jump", sym.JUMP);
          }
        case 39: break;
        case 28: 
          { return sf.newSymbol("Text definition", sym.TEXT_DEF, (new String(yytext())).substring(1));
          }
        case 40: break;
        case 24: 
          { return sf.newSymbol("If", sym.IF);
          }
        case 41: break;
        case 9: 
          { return sf.newSymbol("Mod", sym.MOD);
          }
        case 42: break;
        case 27: 
          { return sf.newSymbol("Number definition", sym.NUM_DEF, (new String(yytext())).substring(1));
          }
        case 43: break;
        case 20: 
          { return sf.newSymbol("Assign Minus", sym.AS_MINUS);
          }
        case 44: break;
        case 3: 
          { /* ignore white space. */
          }
        case 45: break;
        case 21: 
          { return sf.newSymbol("Assign Times", sym.AS_TIMES);
          }
        case 46: break;
        case 38: 
          { return sf.newSymbol("Constant name", sym.CONST_DEF, new String(yytext().substring(6)));
          }
        case 47: break;
        case 7: 
          { return sf.newSymbol("Times", sym.TIMES);
          }
        case 48: break;
        case 35: 
          { return sf.newSymbol("False", sym.FALSE);
          }
        case 49: break;
        case 23: 
          { return sf.newSymbol("Assign", sym.ASSIGN);
          }
        case 50: break;
        case 29: 
          { return sf.newSymbol("End", sym.END);
          }
        case 51: break;
        case 11: 
          { return sf.newSymbol("Right Bracket", sym.RPAREN);
          }
        case 52: break;
        case 8: 
          { return sf.newSymbol("Divide", sym.DIVIDE);
          }
        case 53: break;
        case 26: 
          { return sf.newSymbol("Not Equal", sym.CMP_NE);
          }
        case 54: break;
        case 37: 
          { return sf.newSymbol("Finish", sym.FINISH);
          }
        case 55: break;
        case 33: 
          { return sf.newSymbol("True", sym.TRUE);
          }
        case 56: break;
        case 18: 
          { return sf.newSymbol("Or", sym.BOOL_OR);
          }
        case 57: break;
        case 19: 
          { return sf.newSymbol("Assign Plus", sym.AS_PLUS);
          }
        case 58: break;
        case 12: 
          { return sf.newSymbol("Less", sym.CMP_LT);
          }
        case 59: break;
        case 34: 
          { return sf.newSymbol("Loop", sym.LOOP);
          }
        case 60: break;
        case 15: 
          { return sf.newSymbol("NOT", sym.BOOL_NOT);
          }
        case 61: break;
        case 30: 
          { return sf.newSymbol("Out", sym.IO_OUT);
          }
        case 62: break;
        case 14: 
          { return sf.newSymbol("Equal", sym.CMP_EQ);
          }
        case 63: break;
        case 17: 
          { return sf.newSymbol("Variable name", sym.VAR_NAME, new String(yytext()));
          }
        case 64: break;
        case 6: 
          { return sf.newSymbol("Minus", sym.MINUS);
          }
        case 65: break;
        case 5: 
          { return sf.newSymbol("Plus", sym.PLUS);
          }
        case 66: break;
        case 32: 
          { return sf.newSymbol("Else", sym.ELSE);
          }
        case 67: break;
        case 2: 
          { return sf.newSymbol("Integral Number", sym.NUMBER, new Integer(yytext()));
          }
        case 68: break;
        case 10: 
          { return sf.newSymbol("Left Bracket", sym.LPAREN);
          }
        case 69: break;
        case 16: 
          { return sf.newSymbol("Text", sym.TEXT, new String(yytext()));
          }
        case 70: break;
        case 13: 
          { return sf.newSymbol("Greater", sym.CMP_GT);
          }
        case 71: break;
        case 1: 
          { System.err.println("Illegal character: "+yytext());
          }
        case 72: break;
        case 22: 
          { return sf.newSymbol("Assign Divide", sym.AS_DIV);
          }
        case 73: break;
        case 31: 
          { return sf.newSymbol("And", sym.BOOL_AND);
          }
        case 74: break;
        case 36: 
          { return sf.newSymbol("Begin", sym.BEGIN);
          }
        case 75: break;
        case 25: 
          { return sf.newSymbol("In", sym.IO_IN);
          }
        case 76: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return sf.newSymbol("EOF", sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
