
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 03 08:35:13 ART 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TEXT_DEF = 35;
  public static final int DIVIDE = 5;
  public static final int CMP_NE = 26;
  public static final int LPAREN = 8;
  public static final int AS_DIV = 16;
  public static final int MINUS = 4;
  public static final int CMP_GT = 24;
  public static final int RPAREN = 9;
  public static final int IO_OUT = 17;
  public static final int BEGIN = 11;
  public static final int LOOP = 21;
  public static final int PLUS = 2;
  public static final int ASSIGN = 6;
  public static final int IF = 19;
  public static final int AS_PLUS = 13;
  public static final int EOF = 0;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int JUMP = 10;
  public static final int AS_MINUS = 14;
  public static final int NUMBER = 37;
  public static final int MOD = 7;
  public static final int BOOL_NOT = 29;
  public static final int CMP_LT = 23;
  public static final int BOOL_AND = 28;
  public static final int CONST_DEF = 36;
  public static final int TIMES = 3;
  public static final int ELSE = 20;
  public static final int IO_IN = 18;
  public static final int VAR_NAME = 34;
  public static final int END = 22;
  public static final int FINISH = 12;
  public static final int NUM_DEF = 32;
  public static final int BOOL_OR = 27;
  public static final int TEXT = 33;
  public static final int FALSE = 31;
  public static final int CMP_EQ = 25;
  public static final int AS_TIMES = 15;
}

